networks:
  default:
    name: portfolio_net
    external: true

services:
  frontend:
    container_name: scaletimer-frontend
    build: ./frontend
    expose:
      - "3000"
    depends_on:
      - backend

  backend:
    container_name: scaletimer-backend
    build: ./backend
    expose:
      - "8080"
    depends_on:
      scaletimer-db:
        condition: service_healthy

  scaletimer-db:
    container_name: scaletimer-db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: scaledb
      POSTGRES_USER: aaron
      POSTGRES_PASSWORD: pass
    expose:
      - "5432"
    volumes:
      - scaletimerdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aaron -d scaledb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  scaletimerdata: